laserscan_topic: /scan
sensor_data_topic: /movement_data
scan_publisher: /scan_modified
cmd_vel_publisher: /cmd_vel
target_marker_publisher: /visualization_marker
proportional_factor: 0.5
queueSize: 10

